### ISSUE TITLE
[FEATURE] Build and publish arm64 image

### ISSUE THREAD

**Issue by NTFSvolume** [ne0lith/cdl-docker#2]
This will cover some low power usage machines like the raspberry Pi. 

The build process could also be migrated to a github worker to run every few hours automatically instead of using a cronjob on a local machine.

**Comment by ne0lith** [comment]
Think I've got the action working? Not sure. First time using one, so bear with me!!

Should have both arm64 and amd64

`docker pull ghcr.io/ne0lith/cdl-docker:latest`
`docker pull ne0lith/cdl-docker:latest`
